baseurl = "https://ubogdan.com/"
title = "Bogdan's website"
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-200652301-1" # Enable Google Analytics by entering your tracking id
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsStyle = "dracula"

[Author]
name = "Bogdan Ungureanu"
bio = "Bogdans's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
avatar = "images/logo.jpeg"

[Permalinks]
posts = "/:year/:month/:slug/"
page = "/:slug/"

[Params]
description = "Bogdan's Personal blog about everything"
copyright = "Bogdan U"
opengraph = true
twitter_cards = false
readmore = true # Show "Read more" button in list if true
authorbox = false
pager = true
post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
customCSS = ["css/highlight.css","css/override.css"] # Include custom CSS files


[Params.logo]
image = "images/logo.jpeg" # Logo image. Path relative to "static"
title = "Bogdan Ungureanu" # Logo title, otherwise will use site title
subtitle = "Personal website" # Logo subtitle

[Params.sidebar]
home = "right"   # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
# widgets = ["search", "recent", "categories", "taglist"]
widgets = ["sidemenu", "recent", "categories", "taglist", "social"]

[Params.widgets]
recent_num = 5          # Set the number of articles in the "Recent articles" widget
tags_counter = false    # Enable counter for each tag in "Tags" widget (disabled by default)
