name: CI
on:
  push:
    paths-ignore:
      - 'Makefile'
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.95.0"

      - name: Build
        run: hugo

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload content
        run: aws s3 sync public/ s3://ubogdan.com --delete

      - name: Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E36TAK5X2X8KES --paths "/*"